branches:
  only:
    - master
arch:
  - arm64
  - ppc64le
  - s390x
dist: bionic
language: node_js
before_install: |
  corepack enable
  yarn --version
script:
  - yarn install --immutable
  - yarn build
  - yarn test
node_js:
  - 20
  - 22
  - 24
